# Generated by Django 5.1.4 on 2025-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('water', models.FloatField()),
                ('fat', models.FloatField()),
                ('vitamins', models.FloatField()),
                ('fiber', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('iron', models.FloatField()),
                ('zinc', models.FloatField()),
                ('selenium', models.FloatField()),
                ('copper', models.FloatField()),
                ('manganese', models.FloatField()),
            ],
        ),
    ]
