# Generated by Django 5.1.4 on 2025-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
