# Generated by Django 5.1.4 on 2025-01-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_food_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_img',
            new_name='food_image',
        ),
    ]
